#!/usr/bin/env python3

import argparse
import os
import sys
import textwrap

from pathlib import Path

sys.path.append(str(Path(__file__).parents[1]))
from hephaestus._internal import meta, scripts
from hephaestus.io import (
    command_successful,
    create_directory,
    get_logger,
    run_command,
)

# Constants
VERSION = "1.0.0"
LOG_FILE = Path(meta.Paths.LOGS, "GenerateDocumentation.log")

fail = lambda: exit(1)
logger = get_logger(__name__)


def generate_rst_files():
    """Creates ReStructuredText files from source code docstrings."""
    logger.info("Creating ReStructured Text Files.")
    cmd = [
        "sphinx-apidoc",
        str(meta.Paths.LIB),
        "**/tests/**",
        "--output-dir",
        str(Path(meta.Paths.SPHINX, "source")),
        "--implicit-namespaces",  # Who wants to stick __init__.py everywhere.,
        "--module-first",  # Generate module documentation before generating submodule docs.
        "--separate",  # Generate a file for each module
    ]

    run_command(cmd, err="Failed to create ReStructured Text files.")


def generate_html():
    """Creates HTML from ReStructuredText files."""
    logger.info("Creating HTML Files.")

    # Ensure docs folder exists.
    docs_dir = str(create_directory(meta.Paths.DOCS))

    # Make commands to generate HTML. Note, we change the output dir of HTML files.
    cmd_sets = [
        {
            "cmd": ["make", "clean", f"BUILDDIR={docs_dir}"],
            "on_error": "Failed to clean make environment.",
        },
        {
            "cmd": ["make", "html", f"BUILDDIR={docs_dir}"],
            "on_error": "Failed to create html files.",
        },
    ]

    # Change directory to avoid OS-specific login.
    current_dir = Path.cwd()
    os.chdir(meta.Paths.SPHINX)

    # Run commands changing back to previous directory on failure.
    for cmd_set in cmd_sets:
        run_command(
            cmd_set["cmd"],
            err=cmd_set["on_error"],
            cleanup=lambda: os.chdir(current_dir),
        )

    os.chdir(current_dir)
    logger.info(f"HTML files available here: {docs_dir}")


def _check_sphinx_installation():
    """Verifies system has Sphinx Installed"""
    logger.debug("Verifying Sphinx Apidoc installation")

    cmd = ["sphinx-apidoc", "--version"]

    if not command_successful(cmd):
        logger.error("Could not find Sphinx Apidoc. Is it installed on this machine?")
        fail()


def run():

    parser = argparse.ArgumentParser(
        prog="Generate Source Documentation",
        description="Generates documentation from source code using Sphinx.",
        usage=textwrap.dedent(
            """
            scripts/generate_documentation
            """
        ),
    )

    scripts.add_common_script_args(parser=parser)

    args = parser.parse_args()

    scripts.check_version_arg(script_args=args, script_version=VERSION)
    scripts.set_script_logger(script_args=args, script_log_file=LOG_FILE)

    _check_sphinx_installation()
    generate_rst_files()
    generate_html()


if __name__ == "__main__":
    run()
