#!/usr/bin/env python3

import argparse
import logging
import sys
import textwrap

from pathlib import Path

sys.path.append(str(Path(__file__).parents[1]))
from hephaestus._internal import meta, scripts
from hephaestus.io import configure_root_logger, get_logger

# Constants
VERSION = "1.0.1"
LOG_FILE = Path(meta.Paths.LOGS, "PyTest.log")

fail = lambda: exit(1)
logger = get_logger(root=meta.Paths.ROOT)

# We're running PyTest like a regular Python method here so we can hijack the config options
# for the script. This means we'll have to do some late imports which I don't particularly like,
# but it's a small tradeoff.


def _check_pytest_installation():
    """Verifies system has Pytest Installed"""
    logger.debug("Verifying Pytest installation")

    # TODO: Verify pytest plugins installed too.
    try:
        import pytest
    except ImportError:
        logger.error("Could not find PyTest. Is it installed on this machine?")
        fail()


def run_test_suite(with_color: bool):
    """Uses PyTest to run the test suite.

    Args:
        with_color: whether to color output to stdout.
    """
    import pytest

    logger.info("Starting test suite.")

    pytest_args = [
        "--quiet",
        "-rpfs",  # Show extra summary info for Passed, Failed, and Skipped tests at the end of running.
        "--capture=no",  # Disable capturing output to stdout/stderr.
        "--show-capture=no",  # Don't repeat logs for failed tests.
        "--random-order-bucket=class",  # Run related tests together. Requires pytest-random-order,
        f"--color={'yes' if with_color else 'no'}",
        meta.Paths.LIB,
    ]

    pytest.main(pytest_args)


def run():
    parser = argparse.ArgumentParser(
        prog="Run Hephaestus Test Suite",
        description="Runs the test suite using PyTest.",
        usage=textwrap.dedent(
            """
            scripts/run_pytest
            """
        ),
    )

    scripts.add_common_script_args(parser=parser)

    args = parser.parse_args()

    scripts.check_version_arg(script_args=args, script_version=VERSION)
    scripts.set_script_logger(script_args=args, script_log_file=LOG_FILE)

    logger.info("Script Configuration")
    logger.info(f"Color Enabled: {str(not args.disable_color)}")
    logger.info(f"Verbose Output: {str(args.verbose)}")
    logger.info(f"Log File: {str(LOG_FILE)}")

    _check_pytest_installation()
    run_test_suite(with_color=(not args.disable_color))


if __name__ == "__main__":
    run()
